language: java
sudo: false
install: true
    token:
      secure: 
jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=devops-asset_sonarqube -Dsonar.organization=devops-asset -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
