dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "devops-asset"
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn -q sonar:sonar
  
cache:
  directories:
    - '$HOME/.sonar/cache'
