language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "devops-asset"
    token:
      secure: ${SONAR_TOKEN1}
jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
  -Dsonar.projectKey=devops-asset_sonarqube \
  -Dsonar.organization=devops-asset \
  -Dsonar.host.url=https://sonarcloud.io 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
