dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "devops-asset"
    token: $SONAR_TOKEN1

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
cache:
  directories:
    - '$HOME/.sonar/cache'
