dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "devops-asset"
    token: $SONAR_TOKEN1

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
