dist: trusty
sudo: required

addons:
  sonarcloud:
    projectKey: "devops-asset_sonarqube"
    organization: "devops-asset"
    token:
      secure: ${SONAR_TOKEN}
jdk:
  - oraclejdk8
script:
 - mvn clean verify sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
