language: java
sudo: false
install: true

#addons:
#  sonarcloud:
 #   organization: "devops-asset"
  #  projectKey: "devops-asset_sonarqube"
   # token:
    #  secure: "fefecab8f1786bcec15479e780bf2ad0d4729a8f"!
jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean package sonar:sonar -Dsonar.projectKey=devops-asset_sonarqube -Dsonar.organization=devops-asset -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
  # Adding Sonar Scan 
  #- sonar-scanner 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
